# 抢座脚本用户配置

# 是否启用抢座, true 为启用, false 为禁用
周一:
  启用:  false
  name: 四楼
  开始时间: 10
  持续小时数: 12
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
    - 48
周二:
  启用: true
  name: 四楼
  开始时间: 14
  持续小时数: 8
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
    - 48
周三:
  启用: false
  name: 四楼
  开始时间: 10
  持续小时数: 12
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
    - 48 
    
周四:
  启用: true
  name: 四楼
  开始时间: 10
  持续小时数: 12
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
    - 48 
周五:
  启用: false
  name: 四楼
  开始时间: 10
  持续小时数: 12
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
    - 48
周六:
  启用: false
  name: 四楼
  开始时间: 10
  持续小时数: 12
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
    - 48    # - 另一个备用座位号 (当前脚本未使用，但可以保留)
周日:
  启用: false
  name: 四楼
  开始时间: 10
  持续小时数: 12
  # 要抢的自定义座位号。脚本会抢列表中的第一个座位。
  # 请确保这个座位号是正确的！
  自定义:
    - 58
    - 55
    - 57
    - 54
    - 56
    - 53
    - 52
    - 51
    - 50
    - 47
       # - 另一个备用座位号 (当前脚本未使用，但可以保留)
